site_name: AI Prime Directive — Learn, Build, Iterate.
site_url: https://ozgurgulerx.github.io/ai-prime-directive
repo_url: https://github.com/ozgurgulerx/ai-prime-directive
copyright: © 2025 Ozgur Guler

# Theme configuration for MkDocs Material
theme:
  name: material
  language: en
  logo: images/logo.svg
  icon:
    logo: material/school
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.instant
    - navigation.top
    - content.code.copy
    - content.tooltips
    - toc.follow
    - header.autohide
  palette:
    - scheme: default
      primary: indigo
      accent: emerald
    - scheme: slate
      primary: indigo
      accent: emerald
  custom_dir: overrides

extra_css:
  - styles/extra.css
extra_javascript:
  - js/extra.js

plugins:
  - search
  - blog:
      blog_dir: blog
      blog_toc: true
      pagination_per_page: 10
      authors_file: null
      post_date_format: '%Y-%m-%d'
      draft_on_serve: true
  - tags
  - rss:
      match_path: blog/.*
      date_from_meta:
        as_creation: date
      categories:
        - tags
  - git-revision-date-localized:
      type: timeago
  - minify:
      minify_html: true
  - privacy

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - footnotes
  - def_list
  - md_in_html

nav:
  - Home: index.md
  - Writing: writing/index.md
  - Speaking: speaking/index.md
  - Courses: courses/index.md
  - Consulting: consulting/index.md
  - My Prime Directive:
      - Overview: my-prime-directive/index.md
      - Notes: my-prime-directive/notes.md
      - Start here: my-prime-directive/start.md
      - Foundations:
          - Reasoning Models: my-prime-directive/reasoning-models.md
          - RL in LLMs: my-prime-directive/rl-in-llms.md
      - RAG:
          - Context Engineering: my-prime-directive/context-engineering.md
          - Graph RAG: my-prime-directive/graphrag.md
          - RAG 2.0 — Agentic RAG: my-prime-directive/rag-2-agentic-rag.md
      - Build Patterns:
          - LLM Build Patterns: my-prime-directive/build-patterns-llms.md
          - OpenAI Agent SDK: my-prime-directive/openai-agent-sdk.md
          - Microsoft Semantic Kernel: my-prime-directive/microsoft-semantic-kernel.md
          - Agent Memory: my-prime-directive/agent-apps-memory-engineering.md
          - Agent Frameworks: my-prime-directive/agent-frameworks.md
          - MCP: my-prime-directive/mcp.md
          - Tools — Prompt KV Caching: my-prime-directive/tools-prompt-kv-caching.md
      - Ops:
          - EvalOps: my-prime-directive/evalops.md
          - LLM Apps in Production: my-prime-directive/llm-apps-in-production.md
      - Product:
          - AI UX Design Patterns: my-prime-directive/ai-ux-design-patterns.md
          - Microsoft HAX Framework: my-prime-directive/microsoft-hax-framework.md
  - Books: my-prime-directive/books.md
