site_name: AI Prime Directive — Learn, Build, Iterate.
site_url: https://ozgurgulerx.github.io/ai-prime-directive
repo_url: https://github.com/ozgurgulerx/ai-prime-directive
copyright: © 2025 Ozgur Guler

# Theme configuration for MkDocs Material
theme:
  name: material
  language: en
  logo: images/logo.svg
  icon:
    logo: material/school
  features:
    - navigation.top
    - navigation.tabs
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.code.copy
    - navigation.sections
    - navigation.indexes
    - navigation.instant
    - content.tooltips
    - toc.follow
    - header.autohide
  palette:
    - scheme: default
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  custom_dir: overrides
  font:
    text: Inter
    code: JetBrains Mono

extra_css:
  - assets/styles/extra.css?v=20250906-1514
  - assets/styles/home.css?v=20250906-1514
  - assets/styles/site.css?v=20250906-1514
  - assets/styles/social.css
extra_javascript:
  - assets/js/extra.js?v=20250906-1514
  - assets/js/home.js?v=20250906-1514
  - assets/js/filters.js?v=20250906-1514
  - assets/js/writing.js?v=20250906-1514
  - assets/js/speaking.js?v=20250906-1514

extra:
  social:
    - icon: fontawesome/solid/rss
      link: /feed.xml
      name: RSS
    - icon: fontawesome/brands/twitter
      link: https://x.com/ozgurgulerx
      name: Twitter
    - icon: fontawesome/brands/github
      link: https://github.com/ozgurgulerx
      name: GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/build-relation/newsletter-follow?entityUrn=7267852565411737601
      name: LinkedIn
    - icon: simple/substack
      link: https://generativefrontier.substack.com
      name: Substack
    - icon: fontawesome/solid/envelope
      link: mailto:ozgur@graph-atlas.com
      name: Email
    - icon: fontawesome/solid/calendar-check
      link: "mailto:ozgur@graph-atlas.com?subject=AI%20Talk&body=Hi%20Ozgur,%0A%0AI%27m%20interested%20in%20booking%20a%20talk.%0A%0AVenue:%0ADate:%0AAudience%20details:%0AFormat%20(Keynote%20or%20Tech%20Talk):%0AEvent%20theme:%0A%0AAdditional%20notes:%0A"
      name: Book a talk

plugins:
  - search
  - blog:
      blog_dir: blog
      blog_toc: true
      pagination_per_page: 10
      authors_file: null
      post_date_format: 'yyyy-MM-dd'
      draft_on_serve: true
  - tags
  - rss:
      match_path: ^blog/posts/.*$
      categories:
        - tags
      date_from_meta:
        as_creation: 'date'
      use_git: false
      feed_title: "CloudAtlas Blog"
      length: 20
  - git-revision-date-localized:
      type: timeago
  - minify:
      minify_html: true
  - privacy

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - footnotes
  - def_list
  - md_in_html

nav:
  - Home: index.md
  - Writing: writing/index.md
  - Speaking: speaking/index.md
  - Courses: courses/index.md
  - Consulting:
      - Overview: consulting/index.md
      - Services: consulting/services.md
      - Case Studies: consulting/case-studies.md
  - AI Prime Directive:
      - Overview: prime-directive/index.md
      - LLM Foundations: prime-directive/foundations/index.md
      - Reasoning LLMs: prime-directive/reasoning-llms/index.md
      - RAG: prime-directive/rag/index.md
      - Agents: prime-directive/agents/index.md
      - Open-Source Models: prime-directive/open-source-models/index.md
      - EvalOps: prime-directive/evalops/index.md
      - AI Safety & Security: prime-directive/ai-safety-security/index.md
      - AI UX: prime-directive/product-ux/index.md
      - Graph: prime-directive/graph/index.md
  - Books: books/index.md
  - Blog: blog/index.md
