site_name: AI Prime Directive — Learn, Build, Iterate.
site_url: https://ozgurgulerx.github.io/ai-prime-directive
repo_url: https://github.com/ozgurgulerx/ai-prime-directive
copyright: © 2025 Ozgur Guler

# Theme configuration for MkDocs Material
theme:
  name: material
  language: en
  logo: images/logo.svg
  icon:
    logo: material/school
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - navigation.top
    - content.code.copy
    - content.tooltips
    - toc.follow
    - header.autohide
  palette:
    - scheme: default
      primary: indigo
      accent: emerald
    - scheme: slate
      primary: indigo
      accent: emerald
  custom_dir: overrides

extra_css:
  - styles/extra.css
extra_javascript:
  - js/extra.js

plugins:
  - search
  - blog:
      blog_dir: blog
      blog_toc: true
      pagination_per_page: 10
      authors_file: null
      post_date_format: '%Y-%m-%d'
      draft_on_serve: true
  - tags:
      tags_file: blog/tags.md
  - rss:
      match_path: blog/.*
      date_from_meta:
        as_creation: date
        as_update: false
      categories:
        - tags
  - git-revision-date-localized:
      type: timeago
  - minify:
      minify_html: true
  - privacy

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - footnotes
  - def_list
  - md_in_html

nav:
  - Home: index.md
  - Start here: start.md
  - Prime Directive:
      - Overview: prime-directive/README.md
      - Foundations:
          - prime-directive/foundations/README.md
      - RAG:
          - RAG 2.0: prime-directive/rag/rag-2-0.md
          - Graph RAG: prime-directive/graph/graph-rag.md
      - Agents & Memory:
          - Agent Memory: prime-directive/agents/agent-memory.md
      - EvalOps:
          - prime-directive/evalops/evalops.md
      - Product & UX:
          - prime-directive/product-ux/README.md
  - Writing: blog/index.md
  - Newsletter: newsletter.md
  - Speaking: speaking.md
  - Courses: courses.md
  - Consulting: consulting.md
