site_name: AI Prime Directive — Learn, Build, Iterate.
site_url: https://ozgurgulerx.github.io/ai-prime-directive
repo_url: https://github.com/ozgurgulerx/ai-prime-directive
copyright: © 2025 Ozgur Guler

# Theme configuration for MkDocs Material
theme:
  name: material
  language: en
  logo: images/logo.svg
  icon:
    logo: material/school
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - navigation.top
    - content.code.copy
    - content.tooltips
    - toc.follow
    - header.autohide
  palette:
    - scheme: default
      primary: indigo
      accent: emerald
    - scheme: slate
      primary: indigo
      accent: emerald
  custom_dir: overrides

extra_css:
  - styles/extra.css
extra_javascript:
  - js/extra.js

plugins:
  - search
  - blog:
      blog_dir: blog
      blog_toc: true
      pagination_per_page: 10
      authors_file: null
      post_date_format: '%Y-%m-%d'
      draft_on_serve: true
  - tags:
      tags_file: blog/tags.md
  - rss:
      match_path: blog/.*
      date_from_meta:
        as_creation: date
      categories:
        - tags
  - git-revision-date-localized:
      type: timeago
  - minify:
      minify_html: true
  - privacy

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - footnotes
  - def_list
  - md_in_html

nav:
  - Home:
      - Home: index.md
      - My Prime Directive:
          - AI Prime Directive - Learn building with AI: my-prime-directive.md
          - Notes: notes.md
          - Subscribe: subscribe.md
          - Notebooks: notebooks.md
          - Anki Cards: anki.md
          - Tags: tags.md
          - Foundations:
              - Reasoning Models: reasoning-models.md
              - RL in LLMs: rl-in-llms.md
          - RAG:
              - Context Engineering: context-engineering.md
              - Graph RAG: graphrag.md
              - RAG 2.0 — Agentic RAG: rag-2-agentic-rag.md
          - Build Patterns:
              - LLM Build Patterns: build-patterns-llms.md
              - OpenAI Agent SDK: openai-agent-sdk.md
              - Microsoft Semantic Kernel: microsoft-semantic-kernel.md
              - Agent Memory: agent-apps-memory-engineering.md
              - Agent Frameworks: agent-frameworks.md
              - MCP: mcp.md
              - Tools — Prompt KV Caching: tools-prompt-kv-caching.md
          - Ops:
              - EvalOps: evalops.md
              - LLM Apps in Production: llm-apps-in-production.md
          - Product:
              - AI UX Design Patterns: ai-ux-design-patterns.md
              - Microsoft HAX Framework: microsoft-hax-framework.md
      - Books: books.md
